version = "1.0"

[main]
name = "Pink Arrows settings"

    [main.customization]
    name = "Customization"

        [main.customization.watermark]
        ask = "Watermark"
        type = "file"
        accept = ["image/png"]
        help = "Fill with your own watermark (when the box \"watermark\" is checked, it will be displayed on the bottom right of each picture saved in Pink Arrows)."
        bind = "__INSTALL_DIR__/assets/watermark.png"
