packaging_format = 2
id = "pinkarrows"
name = "Pink Arrows"
description.en = "Lightweight images/screenshot annotation tool"
description.fr = "Outil léger pour l'annotation d'images ou de captures d'écran"
version = "2024.11.19~ynh1"
maintainers = ["oleole39"]

[upstream]
license = "MIT"
demo = "https://pinkarrows.app"
code = "https://github.com/robbalian/pinkarrows"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "8M"
ram.build = "10M"
ram.runtime = "15M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/pinkarrows"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/robbalian/pinkarrows/archive/46ccd45e572b7de43645c09b4e53c63d3a83e6e1.tar.gz"
    sha256 = "6e79cb0c308b84695e333077b03aca831381c1e526c7ed2379c1ff4e373eefdb"
    autoupdate.upstream = "https://github.com/robbalian/pinkarrows"
    autoupdate.strategy = "latest_github_commit"

    [resources.sources.picmo]
    url = "https://registry.npmjs.org/picmo/-/picmo-5.8.5.tgz"
    sha256 = "1c2faee37bbd7f33b1a040955312318c36ff77fd7857c3649ee427ddeb6653b5"
    
    [resources.sources.picmo-popup-picker]
    url = "https://registry.npmjs.org/@picmo/popup-picker/-/popup-picker-5.8.5.tgz"
    sha256 = "dfa3f631df9b96b5073a620876a4147175e3222af8d652f78c0960caf83bc57a"
    
    [resources.sources.emojibase]
    url = "https://github.com/milesj/emojibase/archive/refs/tags/emojibase-data@15.3.2.tar.gz"
    sha256 = "58c7f3f4790bfd3aca72299c92eaa2077056e62517b8a80a7bb843cccdf99021"
    autoupdate.upstream = "https://github.com/milesj/emojibase"
    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "^emojibase-data@(.*)$"
    
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
