packaging_format = 2
id = "pinkarrows"
name = "Pink Arrows"
description.en = "Lightweight images/screenshot annotation tool"
description.fr = "Outil léger pour l'annotation d'images ou de captures d'écran"
version = "1.0~ynh1"
maintainers = ["oleole39"]

[upstream]
license = "MIT"
demo = "https://pinkarrows.app"
code = "https://github.com/robbalian/pinkarrows"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "5M"
ram.build = "60M"
ram.runtime = "20M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/pinkarrows"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/robbalian/pinkarrows/archive/bd673c14cd2a069fdfd1bcf592ebaee1d7222f6b.zip"
    sha256 = "4d21f3d0fcf3193f6891f138e6b3f6f5900d840755282d48c8fc0ab880743c2d"
    autoupdate.upstream = "https://github.com/robbalian/pinkarrows"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
