packaging_format = 2
id = "pinkarrows"
name = "Pink Arrows"
description.en = "Lightweight images/screenshot annotation tool"
description.fr = "Outil léger pour l'annotation d'images ou de captures d'écran"
version = "1.0~ynh1"
maintainers = ["oleole39"]

[upstream]
license = "MIT"
demo = "https://pinkarrows.app"
code = "https://github.com/robbalian/pinkarrows"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "5M"
ram.build = "60M"
ram.runtime = "20M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/pinkarrows"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

	[install.watermark]
	ask = "Watermark"
	type = "file"
	accept = [".png"]
	help = "Fill with your own watermark (when the box \"watermark\" is checked, it will be displayed on the bottom right of each picture saved in Pink Arrows)."
	bind = "__INSTALL_DIR__/assets/watermark.png"
	optional = true

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/robbalian/pinkarrows/archive/bd673c14cd2a069fdfd1bcf592ebaee1d7222f6b.zip"
    sha256 = "4d21f3d0fcf3193f6891f138e6b3f6f5900d840755282d48c8fc0ab880743c2d"
    autoupdate.upstream = "https://github.com/robbalian/pinkarrows"
    autoupdate.strategy = "latest_github_commit"

    [resources.sources.picmo]
    url = "https://registry.npmjs.org/picmo/-/picmo-5.8.5.tgz"
    sha256 = "1c2faee37bbd7f33b1a040955312318c36ff77fd7857c3649ee427ddeb6653b5"
    
    [resources.sources.picmo-popup-picker]
    url = "https://registry.npmjs.org/@picmo/popup-picker/-/popup-picker-5.8.5.tgz"
    sha256 = "dfa3f631df9b96b5073a620876a4147175e3222af8d652f78c0960caf83bc57a"
    
    [resources.sources.emojibase]
    url = "https://github.com/milesj/emojibase/archive/refs/tags/emojibase-data@15.3.2.zip"
    sha256 = "9d4f5509d1ae917b48c147f962a5309d6b74833ae24193443d5200609da7f4ad"
    autoupdate.upstream = "https://github.com/milesj/emojibase"
    autoupdate.strategy = "latest_github_release"
    
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
