#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  # Path to source
  alias __INSTALL_DIR__/;

  # Set correct MJS mime type as it is an unknown filetype to Nginx which
  #   loads related files as 'application/octet-stream' type by default
  include mime.types;
  types {
      application/javascript js mjs;
  }

}
